#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6G
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

# Kotlin/Native Compiler specific memory
kotlin.native.jvmArgs=-Xmx8G

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true